from __future__ import annotations

from datetime import datetime
from collections.abc import Callable
from typing import Protocol
from uuid import UUID

from anchor.domain.admission import RunDispatch, RunReceipt, RunRequest
from anchor.domain.graph import GraphVersion, Trigger
from anchor.domain.project import Project
from anchor.domain.workspace import Workspace, WorkspaceOperation, WorkspaceState
from anchor.domain.models import (ContextSnapshot, EdgeDecision, NodeLease, NodeRun, Run, RunStatus,
                                  Task, VerificationRecord)
from anchor.domain.models import DiagnosticRequest, ProgressEvidence
from anchor.domain.operations import OperationStatus, ToolOperation


class StateStore(Protocol):
    def admit_run(self, request: RunRequest) -> RunReceipt: ...

    def create_task(self, task: Task) -> Task: ...

    def get_task(self, task_id: UUID) -> Task | None: ...

    def publish_graph(self, version: GraphVersion) -> GraphVersion: ...

    def get_graph_version(self, graph_version_id: UUID) -> GraphVersion | None: ...

    def create_trigger(self, trigger: Trigger) -> Trigger: ...

    def list_triggers(self, graph_version_id: UUID) -> list[Trigger]: ...
    def list_active_triggers(self) -> list[Trigger]: ...

    def create_run(self, run: Run) -> Run: ...

    def get_run(self, run_id: UUID) -> Run | None: ...

    def create_node_run(self, node_run: NodeRun) -> NodeRun: ...

    def list_node_runs(self, run_id: UUID) -> list[NodeRun]: ...

    def list_edge_decisions(self, run_id: UUID) -> list[EdgeDecision]: ...

    def get_context_snapshot(self, node_run_id: UUID) -> ContextSnapshot | None: ...

    def list_context_snapshots(self, run_id: UUID) -> list[ContextSnapshot]: ...

    def list_verifications(self, run_id: UUID) -> list[VerificationRecord]: ...

    def pause_run(self, run_id: UUID, *, reason: str, actor: str) -> Run: ...

    def resume_run(self, run_id: UUID, *, reason: str, actor: str) -> Run: ...

    def set_run_archived(self, run_id: UUID, *, archived: bool) -> Run: ...

    def run_graph_index(self) -> dict[UUID, str]: ...

    def run_lifecycle_index(self) -> dict[UUID, dict]: ...

    def list_artifact_references(self) -> list[tuple[UUID, str]]: ...

    def database_bytes(self) -> int | None: ...

    def create_project(self, project: Project) -> Project: ...

    def get_project(self, project_id: str) -> Project | None: ...

    def list_projects(self) -> list[Project]: ...

    def create_workspace(self, workspace: Workspace) -> Workspace: ...

    def get_workspace(self, workspace_id: str) -> Workspace | None: ...

    def list_workspaces(self, *, project_id: str | None = None,
                        state: WorkspaceState | None = None) -> list[Workspace]: ...

    def update_workspace_state(self, workspace_id: str, *, state: WorkspaceState,
                               current_revision: str | None = None) -> Workspace: ...

    def record_workspace_operation(self, operation: WorkspaceOperation) -> WorkspaceOperation: ...

    def list_workspace_operations(self, workspace_id: str) -> list[WorkspaceOperation]: ...

    def get_storage_budgets(self) -> dict[str, int | None]: ...

    def set_storage_budget(self, scope: str, bytes: int | None) -> None: ...

    def protected_run_ids(self) -> set[UUID]: ...

    def purge_run(self, run_id: UUID) -> dict: ...

    def vacuum(self) -> None: ...

    def record_retention_audit(self, *, trigger: str, evicted_runs: int,
                               freed_bytes: int, detail: dict) -> dict: ...

    def list_retention_audit(self, limit: int = 50) -> list[dict]: ...

    def transition_run(
        self,
        *,
        run_id: UUID,
        expected_revision: int,
        status: RunStatus,
        phase: str,
        payload: dict,
        idempotency_key: str,
    ) -> Run: ...

    def append_event(
        self,
        *,
        stream_id: UUID,
        event_type: str,
        payload: dict,
        idempotency_key: str,
    ) -> int: ...

    def list_events(self, stream_id: UUID) -> list[dict]: ...

    def accept_dispatch(self, message: RunDispatch) -> Run: ...

    def accepted_dispatches(self, limit: int = 100) -> list[RunDispatch]: ...

    def record_runtime_heartbeat(self, component: str, instance_id: UUID) -> None: ...

    def runtime_connected(self, component: str, *, within_seconds: int = 15) -> bool: ...

    def claim_ready_node(self, worker_id: str, claim_id: UUID) -> NodeLease | None: ...

    def claim_ready_agent_node(self, worker_id: str, claim_id: UUID) -> NodeLease | None: ...

    def claim_ready_control_node(self, worker_id: str, claim_id: UUID) -> NodeLease | None: ...

    def claim_ready_verifier_node(self, worker_id: str, claim_id: UUID) -> NodeLease | None: ...

    def list_active_leases(self) -> list[NodeLease]: ...

    def heartbeat_node_lease(self, claim_id: UUID, worker_id: str) -> NodeLease: ...
    def recover_model_lease(self, claim_id: UUID, *, reason: str) -> NodeRun: ...
    def recover_node_lease(self, claim_id: UUID, *, reason: str) -> NodeRun: ...


    def complete_node_and_propagate(self, claim_id: UUID, worker_id: str, *, output_ref: str,
                                    input_hashes: dict[str, str] | None = None,
                                    node_input_hash: str | None = None,
                                    input_snapshot: dict[str, object] | None = None,
                                    condition_context: dict[str, object] | None = None,
                                    verification: VerificationRecord | None = None) -> list[NodeRun]: ...

    def fail_node_and_propagate(self, claim_id: UUID, worker_id: str, *, error_code: str,
                                phase: str = "execute",
                                verification: VerificationRecord | None = None,
                                input_snapshot: dict[str, object] | None = None) -> NodeRun: ...

    def retry_node_and_propagate(self, claim_id: UUID, worker_id: str, *, error_code: str,
                                 phase: str = "agent",
                                 error_class: str | None = None,
                                 next_attempt_at: datetime | None = None,
                                 input_snapshot: dict[str, object] | None = None) -> NodeRun: ...

    def register_tool_operation(self, operation: ToolOperation) -> ToolOperation: ...

    def start_tool_operation(self, operation_id: UUID, claim_id: UUID) -> ToolOperation: ...

    def finish_tool_operation(self, operation_id: UUID, claim_id: UUID, *, status: OperationStatus,
                              result_ref: str | None = None, error_code: str | None = None) -> ToolOperation: ...

    def reconcile_tool_operation(self, operation_id: UUID, *, status: OperationStatus,
                                 reconciliation_ref: str, result_ref: str | None = None,
                                 error_code: str | None = None) -> ToolOperation: ...

    def list_tool_operations(self, run_id: UUID) -> list[ToolOperation]: ...

    def get_tool_operation(self, operation_id: UUID) -> ToolOperation | None: ...

    def resolve_reconciled_operation(self, operation_id: UUID, *, actor: str, reason: str,
                                     read_artifact: Callable[[str], str] | None = None) -> NodeRun: ...

    def append_progress_evidence(self, evidence: ProgressEvidence) -> ProgressEvidence: ...
    def list_progress_evidence(self, run_id: UUID) -> list[ProgressEvidence]: ...
    def add_diagnostic_request(self, request: DiagnosticRequest) -> DiagnosticRequest: ...
    def list_open_diagnostics(self, run_id: UUID) -> list[DiagnosticRequest]: ...
    def supersede_diagnostic(self, diagnostic_id: str, *, superseded_by: str) -> DiagnosticRequest: ...
