"""initial canonical state and run admission"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('stream_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stream_id', 'sequence', name=op.f('pk_events')),
    sa.UniqueConstraint('stream_id', 'idempotency_key', name=op.f('uq_events_stream_id'))
    )
    op.create_table('graph_versions',
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('graph_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('graph_version_id', name=op.f('pk_graph_versions')),
    sa.UniqueConstraint('graph_id', 'version', name=op.f('uq_graph_versions_graph_id'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('success_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('last_event_sequence', sa.Integer(), nullable=False),
    sa.Column('workflow_version', sa.Text(), nullable=False),
    sa.Column('context_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.graph_version_id'], name=op.f('fk_runs_graph_version_id_graph_versions')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_runs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_table('triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron', sa.Text(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('filter_expression', sa.Text(), nullable=True),
    sa.Column('idempotency_field', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.graph_version_id'], name=op.f('fk_triggers_graph_version_id_graph_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triggers'))
    )
    op.create_table('node_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('context_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_node_runs_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_runs')),
    sa.UniqueConstraint('run_id', 'node_id', 'attempt', name=op.f('uq_node_runs_run_id'))
    )
    op.create_table('run_outbox',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('envelope', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_outbox_run_id_runs')),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_run_outbox')),
    sa.UniqueConstraint('message_id', name=op.f('uq_run_outbox_message_id')),
    sa.UniqueConstraint('run_id', name=op.f('uq_run_outbox_run_id'))
    )
    op.create_table('run_admissions',
    sa.Column('trigger_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('graph_version_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.graph_version_id'], name=op.f('fk_run_admissions_graph_version_id_graph_versions')),
    sa.ForeignKeyConstraint(['message_id'], ['run_outbox.message_id'], name=op.f('fk_run_admissions_message_id_run_outbox')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_admissions_run_id_runs')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_run_admissions_task_id_tasks')),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], name=op.f('fk_run_admissions_trigger_id_triggers')),
    sa.PrimaryKeyConstraint('trigger_id', 'idempotency_key', name=op.f('pk_run_admissions')),
    sa.UniqueConstraint('run_id', name=op.f('uq_run_admissions_run_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_admissions')
    op.drop_table('run_outbox')
    op.drop_table('node_runs')
    op.drop_table('triggers')
    op.drop_table('runs')
    op.drop_table('tasks')
    op.drop_table('graph_versions')
    op.drop_table('events')
    # ### end Alembic commands ###
